// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OwnerSidebarButtonsController from "./owner_sidebar_buttons_controller"
application.register("owner-sidebar-buttons", OwnerSidebarButtonsController)

import OwnerSignupController from "./owner_signup_controller"
application.register("owner-signup", OwnerSignupController)

import PetShowController from "./pet_show_controller"
application.register("pet-show", PetShowController)

import SidebarButtonsController from "./sidebar_buttons_controller"
application.register("sidebar-buttons", SidebarButtonsController)

import VetEditController from "./vet_edit_controller"
application.register("vet-edit", VetEditController)

import VetSignupController from "./vet_signup_controller"
application.register("vet-signup", VetSignupController)

import VeterinaryViewController from "./veterinary_view_controller"
application.register("veterinary-view", VeterinaryViewController)
